// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJ0qZGnA9tafsU-sbPTyEN73Ak8_i-GY',
    appId: '1:28501173344:android:8f166a31e9ea05fcc78f05',
    messagingSenderId: '28501173344',
    projectId: 'sample-project-25677',
    storageBucket: 'sample-project-25677.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuqX-CF7fokXEMSHOU8TKfN3Rqxk2cnY',
    appId: '1:28501173344:web:a1121f2bf51d5ce9c78f05',
    messagingSenderId: '28501173344',
    projectId: 'sample-project-25677',
    authDomain: 'sample-project-25677.firebaseapp.com',
    storageBucket: 'sample-project-25677.firebasestorage.app',
    measurementId: 'G-RSRV689850',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlrTmPCvPPDhKeMjZyYHv-yjv5oCfJdu4',
    appId: '1:28501173344:ios:b1d074a97b6a0ceac78f05',
    messagingSenderId: '28501173344',
    projectId: 'sample-project-25677',
    storageBucket: 'sample-project-25677.firebasestorage.app',
    iosBundleId: 'com.example.bugTrackerApplication',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrTmPCvPPDhKeMjZyYHv-yjv5oCfJdu4',
    appId: '1:28501173344:ios:b1d074a97b6a0ceac78f05',
    messagingSenderId: '28501173344',
    projectId: 'sample-project-25677',
    storageBucket: 'sample-project-25677.appspot.com',
    iosBundleId: 'com.example.bugTrackerApplication',
  );
}
